define([], function () {
  const headers = {
    Accept: [
      '*/*',
      'application/javascript',
      'application/json',
      'image/*',
      'text/html',
      'text/plain',
    ],
    'Accept-Charset': ['UTF-8', 'UTF-16', 'UTF-32'],
    'Accept-Datetime': [],
    'Accept-Encoding': [
      'aes128gcm',
      'br',
      'compress',
      'deflate',
      'exi',
      'gzip',
      'identity',
      'pack200-gzip',
      'x-compress',
      'x-gzip',
      'zstd',
    ],
    'Accept-Language': [],
    Authorization: [],
    'Cache-Control': [],
    Connection: [],
    'Content-Length': [],
    'Content-MD5': [],
    'Content-Type': [
      'application/javascript',
      'application/json',
      'image/*',
      'text/html',
      'text/plain',
    ],
    Cookie: [],
    Date: [],
    Expect: [],
    Forwarded: [],
    From: [],
    Host: [],
    'If-Match': [],
    'If-Modified-Since': [],
    'If-None-Match': [],
    'If-Range': [],
    'If-Unmodified-Since': [],
    'Max-Forwards': [],
    Origin: [],
    Pragma: [],
    'Proxy-Authorization': [],
    Range: [],
    Referer: [],
    TE: [],
    Upgrade: [],
    'User-Agent': [],
    Via: [],
    Warning: [],
  }
  return headers
})
